/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 new_raw_assets/K-9/K-9_Model.glb --help 
Author: timblewee (https://sketchfab.com/timblewee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/k9-16bb4f352e714c50b6fd5f11e0ed60c5
Title: K9
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/K-9_Model.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" position={[-0.048, 0, 0.022]} rotation={[-1.576, 0, 0.844]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Name_4" position={[-0.001, -0.001, 0]}>
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Silver.001']} />
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Body} />
              </group>
              <group name="Screen_2">
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Black.001']} />
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Screen} />
              </group>
              <group name="Bumper_LR_3" position={[-0.001, 0.231, -0.052]}>
                <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Black.002']} />
              </group>
              <group name="Control_Pad_5">
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Silver} />
                <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Material} />
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Yellow._Em']} />
                <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Blue_Em} />
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Green_Em} />
                <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['Black.001']} />
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Red_Em} />
              </group>
              <group name="Red_Buttons_6">
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Silver} />
                <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.material} />
              </group>
              <group name="Buttons_7">
                <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Silver} />
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.Yellow} />
                <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.material} />
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.White} />
                <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Green} />
              </group>
              <group name="Body_8" position={[-0.001, 0.231, -0.052]}>
                <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Body} />
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Black.002']} />
                <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials['Body.001']} />
              </group>
              <group name="Wheels_9" position={[0, 0.015, 0]}>
                <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Black} />
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Black} />
              </group>
              <group name="Cylinder_10">
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.Material} />
                <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Red_Em} />
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.Silver} />
                <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials['Black.001']} />
              </group>
              <group name="Cube_11" position={[0, 0, -0.242]} scale={[1, 1, 0.667]}>
                <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.Silver} />
              </group>
              <group name="Cylinder001_12" position={[-0.134, 0.205, -0.241]} scale={[1, 0.205, 3.373]}>
                <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.Material} />
              </group>
              <group name="Cube001_13">
                <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.Material} />
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.Blue_Em} />
                <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.Silver} />
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.Red_Em} />
                <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.Black} />
              </group>
              <group name="Cylinder002_14" position={[-0.001, 0, 0.005]}>
                <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.Silver} />
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.Red_Em} />
                <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials['Black.001']} />
              </group>
              <group name="Icosphere_15" position={[-0.139, 0.22, 0.213]}>
                <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.Silver} />
              </group>
              <group name="Plane_16" position={[0, 0.015, 0]}>
                <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.Silver} />
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.Black} />
              </group>
              <group name="Plane001_17" position={[0, 0.295, 0.255]}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.Silver} />
              </group>
              <group name="Circle_18" position={[0, 0.262, 0.253]} rotation={[Math.PI / 2, 0, 0]} scale={1.272}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials['Silver.001']} />
              </group>
              <group name="Handle001_19" position={[0, 0.263, -0.127]}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials['Silver.001']} />
              </group>
              <group name="Bumper_LR001_20">
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials['Black.002']} />
              </group>
              <group name="Eye_Glass_21" position={[0, 0, -0.005]}>
                <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material} />
              </group>
              <group name="Ear_Stalks_22">
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.Body} />
              </group>
              <group name="Head_23">
                <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials['Body.002']} />
              </group>
              <group name="Sucker_24" position={[0, -0.002, -0.004]}>
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.Sucker} />
                <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.Silver} />
              </group>
              <group name="Screws_25">
                <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.Body} />
              </group>
              <group name="Laser_26">
                <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.Silver} />
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.Black} />
              </group>
              <group name="Ears_27">
                <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials['Silver.003']} />
              </group>
              <group name="Nose_Cover_30">
                <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials['Body.001']} />
              </group>
              <group name="Nose_Cover_Cyl_31">
                <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials['Body.001']} />
              </group>
              <group name="Neck_32">
                <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.Black} />
              </group>
              <group name="Collar_33" position={[0, 0.004, 0.003]}>
                <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.Collar} />
                <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.Black} />
              </group>
              <group name="Tail_Gator_34">
                <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.Black} />
              </group>
              <group name="tail_35">
                <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.Silver} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/K-9_Model.glb')
