/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 death_zone_dalek_-_the_five_doctors.glb --transform 
Files: death_zone_dalek_-_the_five_doctors.glb [38.63MB] > /Users/petetreadaway/Projects/3d-chess/new_raw_assets/dalek/death_zone_dalek_-_the_five_doctors-transformed.glb [2.23MB] (94%)
Author: timblewee (https://sketchfab.com/timblewee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/death-zone-dalek-the-five-doctors-12e9d538159445f48548d39f329acf15
Title: Death Zone Dalek - The Five Doctors
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/death_zone_dalek_-_the_five_doctors-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0, 0.781, 0]} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.PaletteMaterial002} position={[0.194, 1.508, -0.023]} rotation={[0, 0.001, -0.716]} scale={0.5} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.PaletteMaterial003} position={[0, 0.984, -0.072]} scale={[1.074, 1.082, 1.074]} />
    </group>
  )
}

useGLTF.preload('/death_zone_dalek_-_the_five_doctors-transformed.glb')
