/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to follow project patterns (PieceMaterial, ModelProps)
Author: Lanzaman (https://sketchfab.com/lanzaboy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberman-b172f58aacea473f8af04c625906f861
Title: Cyberman
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

import { PieceMaterial, ModelProps } from './index'

type GLTFResult = GLTF & {
  nodes: {
    Object_70: THREE.SkinnedMesh
    Object_72: THREE.SkinnedMesh
    Object_74: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
}

export const CybermanModel: React.FC<ModelProps> = (props) => {
  const group = React.useRef<THREE.Group>(null)
  const { scene } = useGLTF('/cyberman.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes } = useGraph(clone) as GLTFResult
  const { color, isSelected, pieceIsBeingReplaced } = props
  const materialProps = { color, isSelected, pieceIsBeingReplaced }

  // Scale to match other pieces - Cyberman is humanoid, adjust scale accordingly
  return (
    <group ref={group} dispose={null} scale={125} position={[0, -0.5, 0]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="9d52be6c04914ef0aaad1a02b5fa4d44fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" position={[0.145, -0.157, -1.952]} rotation={[-Math.PI / 2, 0, 0]} scale={69.527}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh name="Object_70" geometry={nodes.Object_70.geometry} skeleton={nodes.Object_70.skeleton}>
                      <PieceMaterial {...materialProps} />
                    </skinnedMesh>
                    <skinnedMesh name="Object_72" geometry={nodes.Object_72.geometry} skeleton={nodes.Object_72.skeleton}>
                      <PieceMaterial {...materialProps} />
                    </skinnedMesh>
                    <skinnedMesh name="Object_74" geometry={nodes.Object_74.geometry} skeleton={nodes.Object_74.skeleton}>
                      <PieceMaterial {...materialProps} />
                    </skinnedMesh>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cyberman.glb')
