/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to follow project patterns (PieceMaterial, ModelProps)
Author: timblewee (https://sketchfab.com/timblewee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tardis-william-hartnell-era-c89383e2ee694568914530d14ae25d3f
Title: TARDIS - William Hartnell Era
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

import { PieceMaterial, ModelProps } from './index'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_8: THREE.Mesh
    Object_27: THREE.Mesh
    Object_39: THREE.Mesh
    Object_49: THREE.Mesh
    Object_52: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    Phone_Panel: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
  }
}

export const TardisModel: React.FC<ModelProps> = (props) => {
  const { nodes, materials } = useGLTF('/tardis.glb') as unknown as GLTFResult
  const { color, isSelected, pieceIsBeingReplaced } = props
  const materialProps = { color, isSelected, pieceIsBeingReplaced }

  // Scale to match other pieces (compensating for MeshWrapper's 0.03 scale)
  // TARDIS is tall, so we use a smaller scale factor
  return (
    <group dispose={null} scale={130}>
      <mesh geometry={nodes.Object_4.geometry} position={[0, 0.079, 0]}>
        <PieceMaterial {...materialProps} originalMaterial={materials.PaletteMaterial001} />
      </mesh>
      <mesh geometry={nodes.Object_8.geometry} position={[0.057, 2.227, 0.603]} rotation={[Math.PI / 2, 0, 0]} scale={[0.04, 1, 0.04]}>
        <PieceMaterial {...materialProps} originalMaterial={materials.PaletteMaterial002} />
      </mesh>
      <mesh geometry={nodes.Object_27.geometry} position={[0.236, 1.314, 0.543]} rotation={[Math.PI / 2, 1.466, 0]} scale={0.163}>
        <PieceMaterial {...materialProps} originalMaterial={materials.Material} />
      </mesh>
      <mesh geometry={nodes.Object_39.geometry} position={[-0.241, 1.31, 0.537]} scale={[0.794, 22.529, 0.364]}>
        <PieceMaterial {...materialProps} originalMaterial={materials.Phone_Panel} />
      </mesh>
      <mesh geometry={nodes.Object_49.geometry} position={[0, 2.651, 0]} scale={[0.167, 0.25, 0.167]}>
        <PieceMaterial {...materialProps} originalMaterial={materials.PaletteMaterial003} />
      </mesh>
      <mesh geometry={nodes.Object_52.geometry} position={[0, 0.079, 0]}>
        <PieceMaterial {...materialProps} originalMaterial={materials.PaletteMaterial004} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/tardis.glb')
